# Generated by Django 5.2 on 2025-04-11 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConcertHall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("capacity", models.PositiveIntegerField(blank=True, null=True)),
                ("city", models.CharField(max_length=100)),
                ("country_code", models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "code",
                    models.CharField(max_length=3, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="CountryDemographics",
            fields=[
                (
                    "country",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="demographics",
                        serialize=False,
                        to="core.country",
                    ),
                ),
                (
                    "average_online_ticket_purchase_rate",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "average_concert_participation_rate",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "quintile_average_cultural_spending_per_capita",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "annual_average_cultural_spending_per_capita",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "mean_estimated_cultural_expenses_until_2030",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "spotify_streams_total_per_country",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "number_of_tracks_per_country",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "top_chart_presence_per_country",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "average_concert_audience_per_country",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "average_cultural_spending_per_capita",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "country_cluster",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
        ),
    ]
