# Generated by Django 5.2 on 2025-04-11 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_assign_group_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="concerthall",
            name="address",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="concerthall",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="concerthall",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("event_date", models.DateTimeField(blank=True, null=True)),
                (
                    "ticket_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "concert_hall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="core.concerthall",
                    ),
                ),
            ],
        ),
    ]
