# Generated by Django 5.2 on 2025-04-14 12:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_event_organizer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="artist",
        ),
        migrations.AddField(
            model_name="event",
            name="artists",
            field=models.ManyToManyField(
                blank=True, related_name="events", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
