# Generated by Django 5.2 on 2025-04-15 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_remove_genre_genre_category_remove_genre_genre_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="genrefamily",
            old_name="audience_stats",
            new_name="age_group_streams",
        ),
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("spotify_popularity", models.IntegerField(blank=True, null=True)),
                ("longevity", models.IntegerField(blank=True, null=True)),
                ("top_chart_presence", models.IntegerField(blank=True, null=True)),
                (
                    "spotify_streams_total",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("stats_FR", models.IntegerField(blank=True, null=True)),
                ("stats_GB", models.IntegerField(blank=True, null=True)),
                ("stats_DE", models.IntegerField(blank=True, null=True)),
                ("stats_IT", models.IntegerField(blank=True, null=True)),
                ("stats_ES", models.IntegerField(blank=True, null=True)),
                ("stats_BE", models.IntegerField(blank=True, null=True)),
                (
                    "genre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="artists",
                        to="core.genre",
                    ),
                ),
                (
                    "genre_family",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="artists",
                        to="core.genrefamily",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("release_date", models.DateField(blank=True, null=True)),
                ("entry_date", models.DateField(blank=True, null=True)),
                ("entry_rank", models.IntegerField(blank=True, null=True)),
                ("current_rank", models.IntegerField(blank=True, null=True)),
                ("peak_rank", models.IntegerField(blank=True, null=True)),
                ("peak_date", models.DateField(blank=True, null=True)),
                ("appearances", models.IntegerField(blank=True, null=True)),
                ("consecutive_appearances", models.IntegerField(blank=True, null=True)),
                ("streams", models.BigIntegerField(blank=True, null=True)),
                ("source_date", models.DateField(blank=True, null=True)),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracks",
                        to="core.artist",
                    ),
                ),
            ],
        ),
    ]
