# Generated by Django 5.2 on 2025-04-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_rename_audience_stats_genrefamily_age_group_streams_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="followers",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
