# Generated by Django 5.2 on 2025-04-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_artist_followers"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="artist_2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="track",
            name="artist_3",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="track",
            name="artist_others",
            field=models.TextField(blank=True, null=True),
        ),
    ]
