# Generated by Django 5.2 on 2025-04-28 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_assign_generate_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': (('generate_event', 'Peut générer un événement'), ('validate_event', 'Peut valider un événement'))},
        ),
    ]
